name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  # https://stackoverflow.com/a/72408109
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref_name != github.event.repository.default_branch }}

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: pnpm/action-setup@078e9d416474b29c0c387560859308974f7e9c53 # v6.0.1
        with:
          version: latest
          run_install: false

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: .nvmrc
          cache: "pnpm"

      - uses: ./.github/actions/install-safe-chain

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Format check
        run: pnpm format --check

      - name: Test
        run: pnpm test

  build-demo:
    needs: [test]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: pnpm/action-setup@078e9d416474b29c0c387560859308974f7e9c53 # v6.0.1
        with:
          version: latest
          run_install: false

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: .nvmrc
          cache: "pnpm"

      - uses: ./.github/actions/install-safe-chain

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build --base /${{ github.event.repository.name }}/

      - uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: dist/

  deploy-demo:
    needs: [build-demo]
    if: ${{ github.event_name == 'push' && github.ref_name == github.event.repository.default_branch }}

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0

  release:
    needs: [build-demo] # Semantically, this job can be run just after test, but we wait for build-demo to ensure the build is successful.

    if: ${{ github.event_name == 'push' && github.ref_name == github.event.repository.default_branch }}

    permissions:
      contents: write
      pull-requests: write
      id-token: write # Required for OIDC, https://docs.npmjs.com/trusted-publishers#github-actions-configuration

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: pnpm/action-setup@078e9d416474b29c0c387560859308974f7e9c53 # v6.0.1
        with:
          version: latest
          run_install: false

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: .nvmrc
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"

      - uses: ./.github/actions/install-safe-chain

      # Ensure npm 11.5.1 or later is installed for trusted publishing
      - name: Update npm
        # Incremental upgrade of npm through 11.10.0 is needed
        # to avoid the error occurring when directly installing a later version of npm,
        # as reported in https://github.com/npm/cli/issues/9151
        run: |
          npm install -g npm@~11.10.0
          npm install -g npm@latest

      - name: Install dependencies
        run: pnpm install

      - name: Package and Publish
        id: changesets
        uses: changesets/action@6a0a831ff30acef54f2c6aa1cbbc1096b066edaf # v1.7.0
        with:
          publish: pnpm ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
